version: '3.1'

services:
  postgres_database:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_database_data:/var/lib/postgresql/data

volumes:
  postgres_database_data:
    driver: local
